version: "3"
services:
    app:
        build: ./
        restart: always
        ports:
            - 3000:3000
        depends_on:
          - json-server

    json-server:
        build: ./
        restart: always
        ports: 
          - 3004:3004